
# Lista de pacotes essenciais para projetos em R

library(usethis)
library(devtools)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(forcats)
library(readr)
library(plotly)
library(DT)
library(bslib)
library(fmsb)
library(scales)
library(readxl)
library(openxlsx)
library(pacman)
library(fs)
library(here)
library(plumber)
library(httr2)
library(jsonlite)
library(basedosdados)
library(spotifyr)
library(blastula)
library(shiny)
library(shinycssloaders)
library(reticulate)
library(metan)
library(tidytext)
library(renv)
library(targets)
library(DBI)
library(RMariaDB)
library(dbplyr)
library(glue)
library(RColorBrewer)
library(viridis)
library(ggcorrplot)
library(cowplot)
library(hexsession)

hexsession::make_tile()
